spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem://localhost/~/testdb;
    username: sa
    password: